SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE PUBLIC.USERS;
TRUNCATE TABLE PUBLIC.LOAN_INSTALLMENT;
TRUNCATE TABLE PUBLIC.LOAN;
TRUNCATE TABLE PUBLIC.CUSTOMER;
ALTER TABLE PUBLIC.USERS ALTER COLUMN id RESTART WITH 1;
ALTER TABLE PUBLIC.LOAN_INSTALLMENT ALTER COLUMN id RESTART WITH 1;
ALTER TABLE PUBLIC.LOAN ALTER COLUMN id RESTART WITH 1;
ALTER TABLE PUBLIC.CUSTOMER ALTER COLUMN id RESTART WITH 1;
SET REFERENTIAL_INTEGRITY TRUE;

